sudo: required

language: python

services:
  - docker

before_script:
  - python --version
  - docker version
  - docker build -t clarencep/python3-alpine .
  - docker images

script:
  - docker run --rm clarencep/python3-alpine 
